import speciesData from "@/data/species.json";
import { PokemonType } from "./pokemonTypes";

export interface Species {
  /** National Pokedex number. */
  id: number;
  /** PokeAPI slug, e.g. "mr-mime". Matched against during search. */
  name: string;
  /** Display form, e.g. "Mr. Mime". */
  label: string;
  /** Primary type first. Vanilla data — a ROM hack may differ. */
  types: PokemonType[];
  /**
   * Dominant sprite colour as `#RRGGBB`, computed at build time so there is no
   * runtime canvas work, no CORS concern, and no colour pop-in while the sprite
   * decodes. Consumed by the theming slice.
   */
  accent: string;
}

/** Sprites are served from the public directory, keyed by dex number. */
export function spriteUrl(id: number): string {
  return `/sprites/${id}.png`;
}

/**
 * Generated by `npm run build:data`. This is vanilla data and is deliberately
 * treated as a convenience rather than an authority: the hacks this app targets
 * alter typings, and issue #5 adds per-species overrides on top.
 */
export const SPECIES = speciesData as Species[];

const BY_ID = new Map(SPECIES.map((species) => [species.id, species]));

/**
 * Always look the vanilla record up by id rather than holding onto a species
 * object. A resolved species carries overridden types in its `types` field, so
 * re-resolving one would bake a correction in permanently and survive a revert.
 */
export function speciesById(id: number): Species | undefined {
  return BY_ID.get(id);
}
