import speciesData from "@/data/species.json";
import { PokemonType } from "./pokemonTypes";

export interface Species {
  /** National Pokedex number. */
  id: number;
  /** PokeAPI slug, e.g. "mr-mime". Matched against during search. */
  name: string;
  /** Display form, e.g. "Mr. Mime". */
  label: string;
  /** Primary type first. Vanilla data — a ROM hack may differ. */
  types: PokemonType[];
}

/**
 * Generated by `npm run build:data`. This is vanilla data and is deliberately
 * treated as a convenience rather than an authority: the hacks this app targets
 * alter typings, and issue #5 adds per-species overrides on top.
 */
export const SPECIES = speciesData as Species[];

export function findSpeciesById(id: number): Species | undefined {
  return SPECIES.find((s) => s.id === id);
}
